## Makefile

world:
	emacs -batch -q -l compile-file.el -e batch-byte-compile *.el
# mac
#	/Applications/Emacs.app/Contents/MacOS/Emacs -batch -q -l compile-file.el -e batch-byte-compile *.el
#	/Applications/Emacs.app/Contents/MacOS/Emacs -q -l compile-file.el -e batch-native-compile *.el

clean:
	rm -f *~ *.elc
